# BUILD STAGE
# Node.js 18.20.4
FROM node@sha256:a7ff16657263663c1e92ba3060cdbba0e77329a0a4cb3c27bbbbe90c6e20bd87 as builder

WORKDIR /app

# test

# Check .dockerignore for what's ignored
COPY . .

RUN npm install --no-fund &&\
    npm run build

# RUN STAGE
# Node.js 18.20.4-alpine
FROM node@sha256:17514b20acef0e79691285e7a59f3ae561f7a1702a9adc72a515aef23f326729

LABEL maintainer="Raphael Tholl - raphael.tholl@ibm.com"

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

RUN npm install --no-fund --production

EXPOSE 8080

RUN chown -R node:node /app

USER node

CMD ["node", "dist/app.js"]