apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sample-app
spec:
  project: default
  source:
    repoURL: https://github.com/RapTho/service-mesh-demo.git 
    path: sample-app/k8s_resources 
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
