apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: instana-agent
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: instana-pop
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops