apiVersion: v1
kind: Secret
metadata:
  name: github-repo-service-mesh-demo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/RapTho/service-mesh-demo